title: Mon site Jekyll
description: Un simple site généré avec Jekyll.
baseurl: ""
url: "http://example.com"  # Remplace par l'URL de ton site si tu la connais.

theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
